import { Eye, Plus } from "lucide-react"
import { Link } from "react-router-dom"
import { Button } from "@/shared/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/components/ui/table"
import { CuentaCobrarEstadoBadge } from "./CuentaCobrarEstadoBadge"
import type { CuentaCobrar } from "../types/cuentaCobrar.types"
import { clienteNombre, getSaldoCuenta, toNumber } from "../types/cuentaCobrar.types"
const money = (v?: number | string | null) => new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(toNumber(v))
export function CuentasCobrarTable({ cuentas, onPagar }: { cuentas: CuentaCobrar[]; onPagar: (cuenta: CuentaCobrar) => void }) {
  return <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Venta</TableHead><TableHead>Emision</TableHead><TableHead>Vencimiento</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Pagado</TableHead><TableHead className="text-right">Saldo</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{cuentas.map((cuenta) => <TableRow key={cuenta.id}><TableCell className="min-w-56 font-medium"><div>{clienteNombre(cuenta.cliente)}</div><div className="text-xs text-muted-foreground">{cuenta.cliente?.numero_documento ?? "Sin documento"}</div></TableCell><TableCell>{cuenta.venta?.numero_comprobante ?? `#${cuenta.venta_id}`}</TableCell><TableCell>{cuenta.fecha_emision ?? "-"}</TableCell><TableCell>{cuenta.fecha_vencimiento ?? "-"}</TableCell><TableCell className="text-right font-semibold">{money(cuenta.monto_total)}</TableCell><TableCell className="text-right">{money(cuenta.monto_pagado)}</TableCell><TableCell className="text-right font-semibold">{money(getSaldoCuenta(cuenta))}</TableCell><TableCell><CuentaCobrarEstadoBadge estado={cuenta.estado} /></TableCell><TableCell><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" asChild aria-label="Ver detalle"><Link to={`/ventas/cuentas-por-cobrar/${cuenta.id}`}><Eye className="h-4 w-4" /></Link></Button><Button size="icon" variant="ghost" disabled={getSaldoCuenta(cuenta) <= 0 || cuenta.estado === "ANULADO" || cuenta.estado === "ANULADA"} onClick={() => onPagar(cuenta)} aria-label="Registrar pago"><Plus className="h-4 w-4" /></Button></div></TableCell></TableRow>)}</TableBody></Table></div>
}
