import type { ReactNode } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useEffect } from "react"
import { useForm } from "react-hook-form"
import { Button } from "@/shared/components/ui/button"
import { Checkbox } from "@/shared/components/ui/checkbox"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/shared/components/ui/dialog"
import { Input } from "@/shared/components/ui/input"
import { Switch } from "@/shared/components/ui/switch"
import { AppCombobox } from "@/shared/components/forms/AppCombobox"
import { usuarioSchema } from "@/modules/configuracion/usuarios/schemas/usuario.schema"
import type { Role } from "@/modules/configuracion/roles/types/role.types"
import type { Tienda } from "@/modules/configuracion/tiendas/types/tienda.types"
import type { Usuario, UsuarioFormValues } from "@/modules/configuracion/usuarios/types/usuario.types"
import type { LaravelValidationErrors } from "@/shared/services/api"

export function UsuarioModal({ open, usuario, roles, tiendas, serverErrors, isSubmitting, onOpenChange, onSubmit }: { open: boolean; usuario?: Usuario | null; roles: Role[]; tiendas: Tienda[]; serverErrors?: LaravelValidationErrors; isSubmitting?: boolean; onOpenChange: (open: boolean) => void; onSubmit: (values: UsuarioFormValues) => void }) {
  const form = useForm<UsuarioFormValues>({ resolver: zodResolver(usuarioSchema(Boolean(usuario))) as never, defaultValues: { name: "", email: "", password: "", estado: true, roles: [], tiendas: [], tienda_activa_id: null } })
  const selectedRoles = form.watch("roles") ?? []
  const selectedTiendas = form.watch("tiendas") ?? []
  useEffect(() => { if (open) form.reset({ name: usuario?.name ?? "", email: usuario?.email ?? "", password: "", estado: usuario?.estado ?? true, roles: usuario?.roles?.map((r) => r.id) ?? (usuario?.role ? [usuario.role.id] : []), tiendas: usuario?.tiendas?.map((t) => t.id) ?? [], tienda_activa_id: usuario?.tienda_activa?.id ?? null }) }, [open, usuario, form])
  useEffect(() => { Object.entries(serverErrors ?? {}).forEach(([k, v]) => form.setError(k as keyof UsuarioFormValues, { message: v[0] })) }, [serverErrors, form])
  function toggle(field: "roles" | "tiendas", id: number, checked: boolean) { const values = field === "roles" ? selectedRoles : selectedTiendas; form.setValue(field, checked ? [...values, id] : values.filter((x) => x !== id)) }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{usuario ? "Editar usuario" : "Nuevo usuario"}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={form.handleSubmit(onSubmit)}><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre" error={form.formState.errors.name?.message}><Input {...form.register("name")} aria-invalid={!!form.formState.errors.name} /></Field><Field label="Email" error={form.formState.errors.email?.message}><Input {...form.register("email")} aria-invalid={!!form.formState.errors.email} /></Field><Field label={usuario ? "Nueva contraseña" : "Contraseña"} error={form.formState.errors.password?.message}><Input type="password" {...form.register("password")} aria-invalid={!!form.formState.errors.password} /></Field><label className="flex items-center gap-3 pt-8 text-sm"><Switch checked={form.watch("estado")} onCheckedChange={(v) => form.setValue("estado", v)} /> Usuario activo</label></div><div className="grid gap-4 md:grid-cols-2"><section className="rounded-md border p-3"><h3 className="mb-2 text-sm font-semibold">Roles</h3><div className="space-y-2">{roles.map((r) => <label key={r.id} className="flex gap-2 text-sm"><Checkbox checked={selectedRoles.includes(r.id)} onCheckedChange={(v) => toggle("roles", r.id, Boolean(v))} />{r.name}</label>)}</div>{form.formState.errors.roles ? <p className="mt-2 text-sm text-destructive">{form.formState.errors.roles.message}</p> : null}</section><section className="rounded-md border p-3"><h3 className="mb-2 text-sm font-semibold">Tiendas</h3><div className="space-y-2">{tiendas.map((t) => <label key={t.id} className="flex gap-2 text-sm"><Checkbox checked={selectedTiendas.includes(t.id)} onCheckedChange={(v) => toggle("tiendas", t.id, Boolean(v))} />{t.nombre}</label>)}</div>{form.formState.errors.tiendas ? <p className="mt-2 text-sm text-destructive">{form.formState.errors.tiendas.message}</p> : null}</section></div><label className="space-y-2 text-sm font-medium"><span>Tienda activa</span><AppCombobox value={form.watch("tienda_activa_id") ?? null} onChange={(v) => form.setValue("tienda_activa_id", v ? Number(v) : null)} options={tiendas.filter((t) => selectedTiendas.includes(t.id)).map((t) => ({ value: t.id, label: t.nombre, description: t.codigo ?? undefined }))} placeholder="Seleccionar tienda activa" emptyMessage="Primero selecciona tiendas" /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Guardando..." : "Guardar"}</Button></div></form></DialogContent></Dialog>
}
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="space-y-2 text-sm font-medium"><span>{label}</span>{children}{error ? <p className="text-sm text-destructive">{error}</p> : null}</label> }